killbill/killbill-cloud

- docker/README.md
The local development instructions in `docker/README.md` didn't work as provided because
1. The mariadb Docker image doesn't create a database by default, and it was easy to overlook the instruction to create the `killbill` database.
2. The analytics and stripe DDLs don't specify a database, so they fail without specifying the DB on the mysql command line.
3. The instructions to create a database named `killbill_0_16_0` conflict with the main DDL's `use killbill` statement.
I fixed these by adding the `-e MYSQL_DATABASE=killbill` argument to the mariadb container, specifying the `-D killbill` argument to subsequent runs of the mysql client, and changing the Kill Bill container's environment to point back at the `killbill` database instead of `killbill_0_16_0`.
Also I added instructions …
> Some fixes for local development instructions

- kpm/lib/kpm/base_artifact.rb
- kpm/lib/kpm/base_installer.rb
- kpm/lib/kpm/killbill_plugin_artifact.rb
- kpm/spec/kpm/remote/base_artifact_spec.rb
- kpm/spec/kpm/remote/killbill_plugin_artifact_spec.rb
Previously, if references to an artifact were present in the sha file, it wouldn't be installed, even if it didn't exist in the fs
> Make sure packages are re-installed if deleted manually.

- kpm/lib/kpm/inspector.rb
Fixes error: "Not a directory @ dir_initialize - .../plugins/ruby/.DS_Store"
> Make sure we only look at sub-folders and inspecting fs for plugins

- docker/compose/docker-compose.kb.yml
docker-compose puked on "3306:3306" as expose is expected to be  'PORT[/PROTOCOL]'
> Corrected incorrect syntax in docker-compose expose property

- docker/README.md
To following example requires the user to have the mysql client (e.g. Debian package mysql-client) and docker machine installed on the local system.
```echo "set global binlog_format = 'ROW'" | mysql -h $(docker-machine ip default) -u root -proot```
This could be solved by executing the mysql client directly in the running docker container and perform a connection to localhost.
> Remove the requirement of having a mysql client and docker machine installed in the system

- docker/compose/README.md
Hi,
I tried to run the docker compose examples yesterday and I had some problems trying to log into kaui, the culprit was related to changes in the killbill sessions table.
I found that the README in the docker compose page was using an old version to install the DDL, the command uses version 0.16 but the docker :latest image installs 0.18.
This change only fix that minor version problem in the README.
> fix killbill DDL first time install version.

- .gitignore
- ansible/README.md
- ansible/group_vars/all.yml
- ansible/library/killbill
- ansible/library/killbill_facts
- ansible/library/killbill_plugin
- ansible/play.yml
- ansible/plugin.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/killbill/tasks/main.yml
- ansible/roles/killbill/templates/killbill.properties.j2
- ansible/roles/kpm/tasks/main.yml
- ansible/roles/plugins/tasks/main.yml
- ansible/roles/tomcat/handlers/main.yml
- ansible/roles/tomcat/tasks/main.yml
- ansible/roles/tomcat/templates/conf/context.xml.j2
- ansible/roles/tomcat/templates/conf/server.xml.j2
- ansible/roles/tomcat/templates/conf/setenv.sh.j2
- ansible/roles/tomcat/templates/conf/web.xml.j2
- ansible/tomcat.yml
- ansible/tomcat_restart.yml
- ansible/tomcat_ubuntu.yml
Created a PR mostly to track our discussions:
* Consider publishing roles through Ansible Galaxy.
* Re-consider using handlers, as it makes it harder to use them directly. For Tomcat, it's also questionable whether we would ever deploy without restarting it (is it safe enough nowadays to just restart plugins?).
* Consider using these playbooks to build the Docker images.
* Load balancer support has been improved:
* introduced the `org.killbill.server.shutdownDelay` property (to avoid unnecessary `sleep` before stop).
* healthcheck can be manipulated through HTTP APIs (not yet integrated in the playbook).
@andrenpaes feel free to update what I've missed.
> Initial Ansible support

- ansible/templates/killbill/killbill.properties.j2
Make sure we never fallback to the default password.
> ansible: allow for blank DB passwords

- ansible/README.md
- ansible/group_vars/all.yml
- ansible/library/killbill_facts
- ansible/library/killbill_migrations
- ansible/roles/kpm/tasks/main.yml
- ansible/roles/migrations/tasks/main.yml
- ansible/roles/migrations/tasks/migrate.yml
- kpm/lib/kpm/plugins_directory.rb
Wraps `killbill-flyway` and `kpm migrations` in an Ansible playbook. It is never automatically invoked though, it is expected to be run manually.
Work still in progress:
* General cleanup of our Ansible roles and better errors handling
* Update our Docker images to support this
* Update `killbill-docs`
> ansible: Flyway support

- ansible/README.md
- ansible/flyway.yml
- ansible/kaui.yml
- ansible/killbill.yml
- ansible/kpm.yml
- ansible/library/killbill_facts
- ansible/library/killbill_migrations
- ansible/migrations.yml
- ansible/roles/migrations/tasks/flyway.yml
- ansible/roles/migrations/tasks/main.yml
- docker/templates/killbill/latest/Dockerfile
- docker/templates/killbill/latest/kpm.yml
Flyway is now installed in `killbill/killbill:latest` by default. Migrations can be run simply by invoking `$MIGRATIONS_CMD`.
> Flyway support in Docker

- ansible/roles/migrations/tasks/migrate.yml
If existing migrations have already been applied, Flyway will by default validate all of them before migrating.
Our Ansible playbook however only downloads the delta of migrations to run, not the full history: so if there are existing migrations, the playbook would fail.
Flyway has a flag `ignoreMissingMigrations` since 4.1.0, but our binary is still based on 4.0 and upgrading it is quite hard unfortunately.
Luckily `validateOnMigrate` skips that validation as well, so it offers a good workaround for now.
> ansible: skip validations before migration

- kpm/README.adoc
- kpm/lib/kpm/account.rb
- kpm/lib/kpm/diagnostic_file.rb
- kpm/lib/kpm/system.rb
- kpm/lib/kpm/tasks.rb
- kpm/lib/kpm/tenant_config.rb
- kpm/lib/kpm/uninstaller.rb
- kpm/spec/kpm/remote/tenant_config_spec.rb
- kpm/spec/kpm/unit/uninstaller_spec.rb
- kpm/spec/kpm/unit_mysql/account_spec.rb
- kpm/spec/spec_helper.rb
* Fix issue where Tomcat PID wasn't properly detected
* Enhance README with high level description of commands (doesn't replace our documentation though, it's more like a quick reference for us)
* Add `kpm cleanup`
> Add cleanup command

- ansible/group_vars/all.yml
Subset of changes from https://github.com/killbill/killbill-cloud/pull/152 more suitable for `master`.
> ansible: revisit JVM and Tomcat defaults

- docker/README.adoc
When using PostgreSQL, one needs to specify `KAUI_CONFIG_DAO_ADAPTER=postgresql` for Kaui.
Otherwise, Kaui fails to start with the following error:
```
org.jruby.rack.RackInitializationException: No such file to load -- java.lang.StackOverflowError: null.rb
```
> README: document KAUI_CONFIG_DAO_ADAPTER property

- kpm/lib/kpm/account.rb
This is necessary for `split` to work when parsing UTF-8 data.
> kpm: force UTF-8 when opening files

- ansible/templates/kaui/conf/setenv2.sh.j2
- docker/README.adoc
In https://docs.killbill.io/latest/user_management.html#_super_user the `KAUI_ROOT_USERNAME` docker env var is documented to map to the `kaui.root_username` system property, but it looks like that's missing: https://github.com/search?q=org%3Akillbill+KAUI_ROOT_USERNAME&type=Code
I've added it along side the other KAUI docker env vars.
> Add missing KAUI_ROOT_USERNAME docker env var (as documented)

- .github/workflows/kpm_ci.yml
- .github/workflows/kpm_rubocop.yml
- kpm/docker/docker-compose.ci.mysql.yml
- kpm/lib/kpm/nexus_helper/cloudsmith_api_calls.rb
- kpm/spec/kpm/remote/cloudsmith_api_calls_spec.rb
Per @lskillen, don't assume a `maven-metadata.xml` exists for non-SNAPSHOT artifacts.
I've added a regression test on GitHub Actions for this, which pulls from a Cloudsmith test repository:
1. A released artifact
2. A SNAPSHOT artifact (with multiple uploads)
> kpm: Cloudsmith download fix

- docker/templates/mariadb/tagged/Dockerfile.template
- kpm/lib/kpm/account.rb
- kpm/lib/kpm/blob.rb
* In order to be able to LOAD_FILE, we need to configure the `mysqld` with the path of where such files can be loaded. See https://github.com/killbill/killbill-cloud/pull/194/commits/4ca955902ab2cdc7b81d0df280c46698b84796d5
* KPM account needs to be updated to use this temp location: https://github.com/killbill/killbill-cloud/pull/194/commits/934ff38aa62b355e84b1c5931f05d116be1a22db
> docker: Specify a default for mariaddb secure_file_priv

- kpm/kpm.gemspec
This addresses CVE-2019-16892.
> kpm: update rubyzip to 1.3.0

- docker/templates/base/latest/Dockerfile
- docker/templates/kaui/latest/Dockerfile
KPM 0.11.0 is incompatible with Kill Bill 0.22.x, make sure to pin the version in `master`.
Related: https://github.com/killbill/killbill-cloud/pull/213
> docker: lock KPM version for 0.22.x

- docker/dockerTemplate.sh
Fix error:
```
2023-06-21T12:20:06.0344483Z Built templates/mariadb/tagged/Dockerfile with FROM:
2023-06-21T12:20:06.0355511Z FROM mariadb
2023-06-21T12:20:06.0382128Z cat: templates/mariadb/tagged/kpm.yml.template: No such file or directory
```
> docker: fix database build

- docker/templates/mariadb/tagged/Dockerfile.template
Kaui isn't compatible with 11.0 yet.
> docker: pin MariaDB version

- kpm/lib/kpm/plugins_directory.yml
Updated the `groupId` for `catalog-test-plugin` (See [PR](https://github.com/killbill/killbill-catalog-plugin-test/pull/18)). As part of this change, version `5.1` of the `catalog-test-plugin` was released. This PR updates [plugins_directory.yml](https://github.com/killbill/killbill-cloud/compare/fix-plugin-directory?expand=1#diff-0a320713fd016f25c58c4c037a16b0a62766fafba6f3a1ad96be71448c54e5d9) to point to the new version.
> Updated catalog plugin test version

- docker/templates/base/latest/Dockerfile
The [release workflow](https://github.com/killbill/killbill-cloud/blob/e3e2c960e073fe2e703034bca926ab2ff37d52be/.github/workflows/release.yml#L55) currently [fails](https://github.com/killbill/killbill-cloud/actions/runs/8095007126) as there is an issue while cloning the repo. This PR attempts to fix this issue.
> Fix release issue

- docker/templates/kaui/latest/setenv2.sh
Currently, it is required to specify the KAUI_SECRET_KEY_BASE in the docker compose file, otherwise, Kaui does not start.  This PR attempts to fix this issue. 
Note: this change is untested.
> Fix KAUI_SECRET_KEY_BASE issue

- kpm/lib/kpm/diagnostic_file.rb
- kpm/lib/kpm/tasks.rb
> Work for 270

- .github/workflows/kpm_release.yml
KPM release modified for OSSRH migration. Note: `server_id` for snapshot releases is not changed. LMK if this is required.
> KPM release changes for OSSRH migration
