killbill/killbill-cloud

kpm/lib/kpm.rb, kpm/lib/kpm/plugins_manager.rb, kpm/lib/kpm/sha1_checker.rb, kpm/lib/kpm/tasks.rb, kpm/lib/kpm/uninstaller.rb, kpm/spec/kpm/unit/sha1_checker_spec.rb, kpm/spec/kpm/unit/uninstaller_spec.rb, kpm/spec/spec_helper.rb
* Deletes plugin from the fs, asking for confirmation if multiple version are installed
* Cleans up sha1.yml and plugin_identifiers.json files
I'm still working on the specs.
=> Adds uninstall task for removing plugins based on the plugin name/key

kpm/lib/kpm/installer.rb
* Removes "stale" entries from plugin_identifiers.json and sha1.yml files
=> Cleans up descriptors after installing plugins.

docker/templates/base/latest/Dockerfile, docker/templates/build/Dockerfile
=> Update to Ubuntu 16 and Java 8

docker/compose/kibana/Dockerfile
Sense was renamed to Console and is built into Kibana 5.
=>  ERROR  unknown command plugin

kpm/lib/kpm/account.rb, kpm/lib/kpm/database.rb, kpm/lib/kpm/diagnostic_file.rb, kpm/lib/kpm/system.rb, kpm/lib/kpm/tasks.rb, kpm/spec/kpm/unit_mysql/account_spec.rb
Catalina base not always found #105	
kpm diagnostic should accept --bundles-dir #106  	
Enhancements to kpm account --import #107
=> Issues #105; #106 and #107

docker/compose/logstash/config/logstash.conf
This update will add key:value filter. The messages will be splitted by the key=value. Creating new fields to be used in Kibana searches.
=> Pre-configured Kill Bill EE stack with metrics and dashboards #25

ansible/library/killbill_facts, kpm/lib/kpm/system.rb, kpm/tasks/package.rake
https://github.com/killbill/killbill-client-ruby/pull/39
=> Bad kpm-0.6.0 package #114 - fixes

kpm/lib/kpm/diagnostic_file.rb, kpm/lib/kpm/tasks.rb
=> kpm: pass missing port option to diagnostic task

ansible/library/killbill, kpm/lib/kpm/base_artifact.rb, kpm/lib/kpm/nexus_helper/nexus_api_calls_v2.rb
- fixes #124 
- fix when not using default KB nexus
=> Work for release 0.19.x

ansible/roles/tomcat/tasks/restart.yml, docker/templates/base/latest/Dockerfile, docker/templates/killbill/latest/Dockerfile
See https://github.com/killbill/killbill-docs/pull/55.
=> docker: make the start command configurable via START_TOMCAT_OPTS

docker/compose/README.adoc
with memory limit 2GB killbill starts and suddenly stop working caused by low memory
=> mention 4GB memory limit

kpm/lib/kpm/account.rb, kpm/lib/kpm/database.rb, kpm/lib/kpm/tasks.rb, kpm/spec/kpm/unit_mysql/account_spec.rb
See https://github.com/killbill/killbill/pull/1127.
=> KPM import fixes

ansible/README.md, ansible/diagnostic.yml, ansible/flyway.yml, ansible/kaui.yml, ansible/killbill.yml, ansible/kpm.yml, ansible/library/killbill_diagnostics, ansible/library/killbill_facts, ansible/library/killbill_migrations, ansible/migrations.yml, ansible/roles/migrations/tasks/flyway.yml, ansible/roles/migrations/tasks/main.yml, docker/templates/killbill/latest/Dockerfile, docker/templates/killbill/latest/kpm.yml, kpm/lib/kpm/diagnostic_file.rb
https://github.com/killbill/killbill-cloud/pull/145 should be merged first.
=> Integrate kpm diagnostic in Docker

kpm/README.adoc, kpm/lib/kpm/base_installer.rb, kpm/lib/kpm/installer.rb, kpm/lib/kpm/killbill_server_artifact.rb, kpm/lib/kpm/tasks.rb
Various fixes + better integration with the new and improved™ KPM plugin.
=> Improvements iteration v2

kpm/lib/kpm/plugins_directory.rb, kpm/spec/kpm/unit/plugins_directory_spec.rb
=> directory: small regex fix

.circleci/config.yml, kpm/spec/kpm/remote/installer_spec.rb
The Stripe plugin is now a Java one.
=> kpm: fix tests

kpm/README.adoc, kpm/lib/kpm/nexus_helper/actions.rb, kpm/lib/kpm/nexus_helper/cloudsmith_api_calls.rb, kpm/lib/kpm/tasks.rb, kpm/spec/kpm/remote/cloudsmith_api_calls_spec.rb
Verified that KPM can pull releases and SNAPSHOTs.
=> kpm: initial Cloudsmith support

ansible/templates/kaui/conf/setenv2.sh.j2, docker/README.adoc
See https://github.com/killbill/killbill-admin-ui-standalone/issues/39.
=> ansible: make client timeouts configurable in Kaui

.github/workflows/release.yml
This ensures the latest DDL is always present in the images.
=> workflows: release latest database Docker images

.github/workflows/ansible_lint.yml, .github/workflows/docker_ci.yml, ansible/group_vars/all.yml, ansible/java.yml, ansible/kpm.yml, ansible/roles/kaui/tasks/json_logging.yml, ansible/roles/killbill/tasks/main.yml, ansible/roles/kpm/tasks/main.yml, ansible/roles/migrations/tasks/flyway.yml, ansible/roles/migrations/tasks/migrate.yml, ansible/roles/tomcat/tasks/install.yml, ansible/roles/tomcat/tasks/java.yml, ansible/roles/tomcat/tasks/json_logging.yml, ansible/roles/tomcat/tasks/main.yml, ansible/roles/tomcat/tasks/native.yml, ansible/roles/tomcat/tasks/stop.yml, ansible/templates/killbill/kpm.yml.j2, ansible/templates/tomcat/conf/setenv.sh.j2, ansible/tomcat.yml, docker/templates/base/latest/Dockerfile, docker/templates/killbill/latest/Dockerfile, docker/templates/killbill/latest/kpm.yml
This fixes https://github.com/killbill/killbill-cloud/issues/198 and various other small issues (e.g. hardcoded versions).
Going through the individual commit messages might be easier than reading the whole diff.
=> Ansible fixes

ansible/templates/killbill/killbill.properties.j2
See https://github.com/killbill/killbill-commons/pull/97.
=> ansible: make queues shutdown sequence timeout configurable

.github/workflows/ansible_lint.yml
See https://github.com/ansible-community/ansible-lint/issues/1795.
=> .github: fix Ansible lint CI

.github/workflows/ansible_lint.yml, ansible/README.md, ansible/group_vars/all.yml, ansible/java.yml, ansible/templates/tomcat/conf/setenv.sh.j2, docker/templates/base/latest/Dockerfile, docker/templates/build/Dockerfile
Docker images start. More work required to tweak GC flags.
=> Switch to JDK 11

ansible/roles/kaui/tasks/json_logging.yml, ansible/roles/tomcat/tasks/json_logging.yml
Now getting:
```
ERROR! couldn't resolve module/action 'community.general.maven_artifact'. This often indicates a misspelling, missing collection, or incorrect module path.
```
=> ansible: fix build

kpm/kpm.gemspec
Dependabot doesn't have access to secrets.
=> Dependabot merges

kpm/lib/kpm/plugins_directory.yml
- Added plugin versions for `0.22.x` and `0.24.x` wherever applicable
- Did not do any clean up as this will be deprecated soon.
=> updated plugin versions

docker/templates/mariadb/tagged/Dockerfile.template
See https://mariadb.com/kb/en/mariadb-11-0-1-release-notes/#docker-official-images.
=> mariadb: update CMD

.github/workflows/kpm_ci.yml, docker/templates/kaui/latest/setenv2.sh
=> Kaui upgrade

.github/workflows/kpm_ci.yml, ansible/roles/tomcat/tasks/install.yml, docker/README.adoc
- Updated ansible scripts
- Updated Readme
=> Work for tomcat 9 upgrade

kpm/lib/kpm/diagnostic_file.rb, kpm/lib/kpm/tasks.rb
- Remove db related options from help/code
- Removed `--override`/`--ssl-verify` from `class_option` and added them as `method_option` as required
=> Work for 270

.github/workflows/kpm_ci.yml, kpm/kpm.gemspec
Handle this issue: https://github.com/killbill/killbill-stripe-plugin/actions/runs/13521660409/job/37782399343
=> Remove killbill-client dependency version

.github/workflows/kpm_release.yml, kpm/lib/kpm/version.rb, kpm/pom.xml
Changes to get kpm_release to work. Includes the following:
- Update to `ubuntu-22.04` 
- Updated `libgdbm5` to `libgdbm6` and `libssl1.0-dev` to `libssl-dev`
=> Fix kpm release

ansible/group_vars/all.yml, ansible/roles/kpm/tasks/main.yml
Changes for OSSRH migration. Released Docker image for Kaui 3.0.20 with these changes.
=> Ossrh migration

.github/workflows/docker_ci.yml, kpm/lib/kpm/base_artifact.rb, kpm/lib/kpm/nexus_helper/actions.rb, kpm/lib/kpm/nexus_helper/maven_central_api_calls.rb, kpm/lib/kpm/nexus_helper/nexus_api_calls_v2.rb, kpm/lib/kpm/tasks.rb, kpm/spec/kpm/remote/killbill_plugin_artifact_spec.rb, kpm/spec/kpm/remote/maven_central_api_calls_spec.rb
Related issue: https://github.com/killbill/killbill-cloud/issues/291
- Update: New helper for Maven Central API
- Move all the https://oss.sonatype.org URLs to https://repo1.maven.org/maven2
- Spec test for  Maven Central API
=> Work for 291

kpm/lib/kpm/version.rb, kpm/packaging/Gemfile, kpm/packaging/kpm.sh, kpm/pom.xml
Updated pom for kpm release. Released version 0.12.1 with these changes.
=> Reshma debug release
